<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>254d6869-a405-4f8e-93c3-f5c6c81848d4</elementGuidId>
    <imagePath></imagePath>
    <name>div_react_select_2_option_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#react-select-2-option-1</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'react-select-2-option-1') and equals(@class,' css-yt9ioa-option')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value> css-yt9ioa-option</value>
        <webElementGuid>59425011-47d4-4eab-a611-303adab0be1b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>react-select-2-option-1</value>
        <webElementGuid>16c55bc4-119e-4883-99de-f2682fdc50b2</webElementGuid>
    </webElementProperties>
</WebElementEntity>